name: Build and Publish Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/release-notes-generator @semantic-release/exec

    - name: Build package
      run: python -m build

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Publish package
      if: success()
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
