name: Build and Publish Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Necessary permissions for the workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/release-notes-generator @semantic-release/exec semantic-release-pypi

    - name: Generate Release Version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: npx semantic-release

    - name: Build package
      run: python -m build

    - name: Publish package
      if: success()
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
